# Generated by Django 2.2.18 on 2021-09-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_student_favorite_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='favorite_num',
            field=models.IntegerField(null=True),
        ),
    ]
