# Generated by Django 2.2.18 on 2021-10-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_auto_20210927_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mockUserFirstName', models.CharField(max_length=50)),
            ],
        ),
    ]
