# Generated by Django 2.2.18 on 2021-10-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0036_mockstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockstudent',
            name='mockUserGraduatingClass',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mockstudent',
            name='mockUserLastName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
